application: simdott02
version: 1
runtime: python
api_version: 1

handlers:
- url: /main.py
  script : main.py

- url: /debug.py
  script : debug.py
  
- url: /trans
  script : chart_analyzer.py
  

- url: /AppRankingHistory
  script : redirector.py
  
- url: /ViewDataCreator
  script : view_data_creator.py
 
- url: /html
  static_dir : html
  